// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFc-MjLaGYr66OXuo3V1f603DrXkgWsgU',
    appId: '1:295392626479:web:YOUR_WEB_APP_ID',
    messagingSenderId: '295392626479',
    projectId: 'greenconnect2-bc043',
    authDomain: 'greenconnect2-bc043.firebaseapp.com',
    storageBucket: 'greenconnect2-bc043.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFc-MjLaGYr66OXuo3V1f603DrXkgWsgU',
    appId: '1:295392626479:android:33bf47c265599f3cd303da',
    messagingSenderId: '295392626479',
    projectId: 'greenconnect2-bc043',
    storageBucket: 'greenconnect2-bc043.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFc-MjLaGYr66OXuo3V1f603DrXkgWsgU',
    appId: '1:295392626479:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '295392626479',
    projectId: 'greenconnect2-bc043',
    storageBucket: 'greenconnect2-bc043.firebasestorage.app',
    iosBundleId: 'com.example.greenconnect2',
  );
}
